CREATE DATABASE [MesProduction]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MesProduction', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\MesProduction.mdf' , SIZE = 1048576KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MesProduction_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.MSSQLSERVER\MSSQL\DATA\MesProduction_log.ldf' , SIZE = 524288KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [MesProduction] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [MesProduction] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MesProduction] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MesProduction] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MesProduction] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MesProduction] SET ARITHABORT OFF 
GO
ALTER DATABASE [MesProduction] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MesProduction] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MesProduction] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [MesProduction] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MesProduction] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MesProduction] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MesProduction] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MesProduction] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MesProduction] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MesProduction] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MesProduction] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MesProduction] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MesProduction] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MesProduction] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MesProduction] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MesProduction] SET  READ_WRITE 
GO
ALTER DATABASE [MesProduction] SET RECOVERY FULL 
GO
ALTER DATABASE [MesProduction] SET  MULTI_USER 
GO
ALTER DATABASE [MesProduction] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MesProduction] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MesProduction] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MesProduction]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [MesProduction]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [MesProduction] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

USE [MesProduction]
GO
CREATE USER [MesAccount] FOR LOGIN [MesAccount]
GO
USE [MesProduction]
GO
ALTER ROLE [db_datareader] ADD MEMBER [MesAccount]
GO
USE [MesProduction]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [MesAccount]
GO